NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/13-250-172-50-7054-ca-main.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/13-250-172-50-7054-ca-main.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/13-250-172-50-7054-ca-main.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/13-250-172-50-7054-ca-main.pem
    OrganizationalUnitIdentifier: orderer
