---
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: true
    force_apt_get: true
  tags:
    - docker

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    [
      "apt-transport-https",
      "ca-certificates",
      "curl",
      "software-properties-common",
      "python3-pip",
      "virtualenv",
      "python3-setuptools",
    ]
  tags:
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce
  apt:
    update_cache: true
    name: docker-ce
    state: latest
  tags:
    - docker

- name: Install Docker Module for Python
  pip:
    name: docker
  tags:
    - docker

- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present
  tags:
    - docker

- name: Add remote user to "docker" group
  user:
    name: "{{ ansible_ssh_user }}"
    group: "{{ docker_group }}"
    append: true
  tags:
    - docker

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
    update_cache: true
  tags:
    - docker
