---
- name: Update apt packages
  apt:
    update_cache: true
  tags:
    - system

- name: Import docker tasks
  include_tasks: docker.yml

- name: Remove useless apt packages from the cache
  apt:
    autoclean: true
  tags:
    - system

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true
  tags:
    - system
